In [9]:
from sklearn.datasets import load_iris, fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [ ]:
X, y=load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [ ]:
scaler=StandardScaler()
# take mean, std, variance from the sample and do calculations, to get trained data in a scaled way
X_train_scaled=scaler.fit_transform(X_train)
# fit transform: learning these value and do calculations
X_test_scaled=scaler.transform(X_test)
# just do tranform because use same calculations as before
"""
# zero centered the data and bring it to unit variance
(X_train - np.mean(X_train, axis=0))/np.std(X_train, axis=0)
"""
X_train_scaled

array([[ 2.26993576, -0.25863986,  1.36366852,  1.45442273],
       [ 0.6017415 , -1.89215477,  0.43171416,  0.19518227],
       [-0.35151236,  0.9081565 , -1.26773204, -1.18998223],
       [ 1.07836843, -0.02528059,  0.43171416,  0.32110632],
       [-0.82813929,  0.67479723, -1.15809035, -1.18998223],
       [ 0.6017415 , -0.72535841,  0.81546007,  0.44703036],
       [ 0.6017415 ,  0.67479723,  1.0895643 ,  1.58034678],
       [ 1.07836843,  0.44143796,  1.14438514,  1.20257464],
       [-0.94729603,  0.9081565 , -1.26773204, -1.06405819],
       [-0.23235563, -0.25863986,  0.26725162,  0.19518227],
       [-0.1131989 , -0.72535841,  0.486535  ,  0.19518227],
       [-1.06645276, -1.42543622,  0.486535  ,  0.69887846],
       [-0.23235563, -0.95871768,  0.32207247,  0.19518227],
       [-1.18560949, -0.25863986, -1.2129112 , -1.06405819],
       [ 0.6017415 , -1.42543622,  0.76063923,  0.95072655],
       [ 2.26993576, -1.19207695,  1.80223528,  1.45442273],
       [-0.94729603,  1.

In [ ]:
scaler=MinMaxScaler()
# similiar to standard scaler, but press all the value to be 0-1
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
X_train_scaled
"""
X_min=np.min(X_train, axis=0)
X_max=np.max(X_train, axis=0)
(X_train - X_min)/(X_max - X_min)
"""

array([[0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.19444444, 0.41666667,

In [6]:
data=fetch_openml("car", as_frame=True).frame
data

c:\Users\limyt\OneDrive\Documents\VSCode\Scikit-learn\.venv-1\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


,buying,maint,doors,persons,lug_boot,safety,binaryClass
0,vhigh,vhigh,2,2,small,low,P
1,vhigh,vhigh,2,2,small,med,P
2,vhigh,vhigh,2,2,small,high,P
3,vhigh,vhigh,2,2,med,low,P
4,vhigh,vhigh,2,2,med,med,P
...,...,...,...,...,...,...,...
1723,low,low,5more,more,med,med,N
1724,low,low,5more,more,med,high,N
1725,low,low,5more,more,big,low,P
1726,low,low,5more,more,big,med,N


In [ ]:
# ordinal encoder turn into numbers (that can fit machine algorithims)
columns_to_encode=["lug_boot", "safety"]

encoder=OrdinalEncoder(
    categories=[
        ["small", "med", "big"], 
        ["low", "med", "high"]
    ]
)

data[columns_to_encode]=encoder.fit_transform(data[columns_to_encode])
data


,buying,maint,doors,persons,lug_boot,safety,binaryClass
0,vhigh,vhigh,2,2,0.0,0.0,P
1,vhigh,vhigh,2,2,0.0,1.0,P
2,vhigh,vhigh,2,2,0.0,2.0,P
3,vhigh,vhigh,2,2,1.0,0.0,P
4,vhigh,vhigh,2,2,1.0,1.0,P
...,...,...,...,...,...,...,...
1723,low,low,5more,more,1.0,1.0,N
1724,low,low,5more,more,1.0,2.0,N
1725,low,low,5more,more,2.0,0.0,P
1726,low,low,5more,more,2.0,1.0,N


In [ ]:
# one hot encoder turns multiple values for an individual feature into multiple columns that can be 0 or 1
data=fetch_openml("adult", as_frame=True).frame
data

c:\Users\limyt\OneDrive\Documents\VSCode\Scikit-learn\.venv-1\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K


In [10]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [12]:
encoder=OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded_value=encoder.fit_transform(data[["occupation", "race"]])
new_columns=encoder.get_feature_names_out(["occupation", "race"])

In [13]:
encoded_value

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [14]:
new_columns

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [15]:
df_encoded=pd.DataFrame(encoded_value, columns=new_columns, index=data.index)
data_final=pd.concat(
    [data.drop(columns=["occupation", "race"]), df_encoded], axis=1
)
data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,...,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516,Bachelors,13,Never-married,Not-in-family,Male,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,Private,215646,HS-grad,9,Divorced,Not-in-family,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,Private,234721,11th,7,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Not-in-family,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,4,NaN,321403,HS-grad,9,Widowed,Other-relative,Male,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,2,Private,83891,Bachelors,13,Divorced,Own-child,Male,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
