In [1]:
# train classifier and make predictions
from sklearn.datasets import load_breast_cancer
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
X, y=load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
# classifier method doesn't matter much
clf=KNeighborsClassifier()
# train the data
clf.fit(X_train_scaled, y_train)
# how well it performs
clf.score(X_test_scaled, y_test)

0.9473684210526315

In [10]:
single_instance=X_test_scaled[0]
single_instance

array([-1.36030468, -1.50436923, -1.23439177, -1.13330166,  4.90641076,
        2.20871064,  0.11134814,  0.09719346,  2.0864349 ,  4.77012983,
        0.00633233, -0.23676806,  0.06561817, -0.43178147,  0.91412729,
        1.0916921 ,  0.12831783,  1.68473957,  0.58612753,  2.75100757,
       -1.22478363, -1.5154477 , -1.11998682, -1.00738436,  2.55502257,
        0.5619417 , -0.280631  , -0.16538167,  0.23741611,  2.32035867])

In [11]:
# predict malignant/benign
clf.predict([single_instance])

array([1])

In [ ]:
# see if prediction corrects
y_test[0]

np.int64(1)

In [ ]:
# predict probability: 40% 0, 60% 1
# not every classifier supports this
clf.predict_proba([single_instance])

array([[0.4, 0.6]])